import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ModalProviders from "@/components/providers/model-providers";
import { Toaster } from "@/components/ui/sonner";
import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        <ModalProviders />
        <main className="flex h-full w-full">
          <Sidebar />
          <Navbar />
          <div className="flex-1 h-full w-full">{children}</div>
        </main>
      </body>
    </html>
  );
}
